// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dht.proto

// Protobuf Java Version: 3.25.5
package org.decentwallet.wallet.android.dht.proto;

public final class DhtProtos {
  private DhtProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dht_pb_Message_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dht_pb_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dht_pb_Message_Peer_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_dht_pb_Message_Peer_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tdht.proto\022\006dht.pb\032\014record.proto\"\360\003\n\007Me" +
      "ssage\022)\n\004type\030\001 \001(\0162\033.dht.pb.Message.Mes" +
      "sageType\022\013\n\003key\030\002 \001(\014\022!\n\006record\030\003 \001(\0132\021." +
      "record.pb.Record\022)\n\013closerPeers\030\010 \003(\0132\024." +
      "dht.pb.Message.Peer\022+\n\rproviderPeers\030\t \003" +
      "(\0132\024.dht.pb.Message.Peer\022\027\n\017clusterLevel" +
      "Raw\030\n \001(\005\032U\n\004Peer\022\n\n\002id\030\001 \001(\014\022\r\n\005addrs\030\002" +
      " \003(\014\0222\n\nconnection\030\003 \001(\0162\036.dht.pb.Messag" +
      "e.ConnectionType\"i\n\013MessageType\022\r\n\tPUT_V" +
      "ALUE\020\000\022\r\n\tGET_VALUE\020\001\022\020\n\014ADD_PROVIDER\020\002\022" +
      "\021\n\rGET_PROVIDERS\020\003\022\r\n\tFIND_NODE\020\004\022\010\n\004PIN" +
      "G\020\005\"W\n\016ConnectionType\022\021\n\rNOT_CONNECTED\020\000" +
      "\022\r\n\tCONNECTED\020\001\022\017\n\013CAN_CONNECT\020\002\022\022\n\016CANN" +
      "OT_CONNECT\020\003B8\n)org.decentwallet.wallet." +
      "android.dht.protoB\tDhtProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.decentwallet.wallet.android.dht.proto.RecordProtos.getDescriptor(),
        });
    internal_static_dht_pb_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dht_pb_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dht_pb_Message_descriptor,
        new java.lang.String[] { "Type", "Key", "Record", "CloserPeers", "ProviderPeers", "ClusterLevelRaw", });
    internal_static_dht_pb_Message_Peer_descriptor =
      internal_static_dht_pb_Message_descriptor.getNestedTypes().get(0);
    internal_static_dht_pb_Message_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_dht_pb_Message_Peer_descriptor,
        new java.lang.String[] { "Id", "Addrs", "Connection", });
    org.decentwallet.wallet.android.dht.proto.RecordProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
