// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dht.proto

// Protobuf Java Version: 3.25.5
package org.decentwallet.wallet.android.dht.proto;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:dht.pb.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.dht.pb.Message.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.dht.pb.Message.MessageType type = 1;</code>
   * @return The type.
   */
  org.decentwallet.wallet.android.dht.proto.Message.MessageType getType();

  /**
   * <code>bytes key = 2;</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>.record.pb.Record record = 3;</code>
   * @return Whether the record field is set.
   */
  boolean hasRecord();
  /**
   * <code>.record.pb.Record record = 3;</code>
   * @return The record.
   */
  org.decentwallet.wallet.android.dht.proto.Record getRecord();
  /**
   * <code>.record.pb.Record record = 3;</code>
   */
  org.decentwallet.wallet.android.dht.proto.RecordOrBuilder getRecordOrBuilder();

  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer>
      getCloserPeersList();
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  org.decentwallet.wallet.android.dht.proto.Message.Peer getCloserPeers(int index);
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  int getCloserPeersCount();
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  java.util.List<? extends org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
      getCloserPeersOrBuilderList();
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder getCloserPeersOrBuilder(
      int index);

  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer>
      getProviderPeersList();
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  org.decentwallet.wallet.android.dht.proto.Message.Peer getProviderPeers(int index);
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  int getProviderPeersCount();
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  java.util.List<? extends org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
      getProviderPeersOrBuilderList();
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder getProviderPeersOrBuilder(
      int index);

  /**
   * <code>int32 clusterLevelRaw = 10;</code>
   * @return The clusterLevelRaw.
   */
  int getClusterLevelRaw();
}
