// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dht.proto

// Protobuf Java Version: 3.25.5
package org.decentwallet.wallet.android.dht.proto;

/**
 * <pre>
 * Wire schema from libp2p/go-libp2p-kad-dht/pb/dht.proto.
 * </pre>
 *
 * Protobuf type {@code dht.pb.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:dht.pb.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    type_ = 0;
    key_ = com.google.protobuf.ByteString.EMPTY;
    closerPeers_ = java.util.Collections.emptyList();
    providerPeers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.decentwallet.wallet.android.dht.proto.Message.class, org.decentwallet.wallet.android.dht.proto.Message.Builder.class);
  }

  /**
   * Protobuf enum {@code dht.pb.Message.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PUT_VALUE = 0;</code>
     */
    PUT_VALUE(0),
    /**
     * <code>GET_VALUE = 1;</code>
     */
    GET_VALUE(1),
    /**
     * <code>ADD_PROVIDER = 2;</code>
     */
    ADD_PROVIDER(2),
    /**
     * <code>GET_PROVIDERS = 3;</code>
     */
    GET_PROVIDERS(3),
    /**
     * <code>FIND_NODE = 4;</code>
     */
    FIND_NODE(4),
    /**
     * <code>PING = 5;</code>
     */
    PING(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PUT_VALUE = 0;</code>
     */
    public static final int PUT_VALUE_VALUE = 0;
    /**
     * <code>GET_VALUE = 1;</code>
     */
    public static final int GET_VALUE_VALUE = 1;
    /**
     * <code>ADD_PROVIDER = 2;</code>
     */
    public static final int ADD_PROVIDER_VALUE = 2;
    /**
     * <code>GET_PROVIDERS = 3;</code>
     */
    public static final int GET_PROVIDERS_VALUE = 3;
    /**
     * <code>FIND_NODE = 4;</code>
     */
    public static final int FIND_NODE_VALUE = 4;
    /**
     * <code>PING = 5;</code>
     */
    public static final int PING_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return PUT_VALUE;
        case 1: return GET_VALUE;
        case 2: return ADD_PROVIDER;
        case 3: return GET_PROVIDERS;
        case 4: return FIND_NODE;
        case 5: return PING;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.decentwallet.wallet.android.dht.proto.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dht.pb.Message.MessageType)
  }

  /**
   * Protobuf enum {@code dht.pb.Message.ConnectionType}
   */
  public enum ConnectionType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NOT_CONNECTED = 0;</code>
     */
    NOT_CONNECTED(0),
    /**
     * <code>CONNECTED = 1;</code>
     */
    CONNECTED(1),
    /**
     * <code>CAN_CONNECT = 2;</code>
     */
    CAN_CONNECT(2),
    /**
     * <code>CANNOT_CONNECT = 3;</code>
     */
    CANNOT_CONNECT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NOT_CONNECTED = 0;</code>
     */
    public static final int NOT_CONNECTED_VALUE = 0;
    /**
     * <code>CONNECTED = 1;</code>
     */
    public static final int CONNECTED_VALUE = 1;
    /**
     * <code>CAN_CONNECT = 2;</code>
     */
    public static final int CAN_CONNECT_VALUE = 2;
    /**
     * <code>CANNOT_CONNECT = 3;</code>
     */
    public static final int CANNOT_CONNECT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ConnectionType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ConnectionType forNumber(int value) {
      switch (value) {
        case 0: return NOT_CONNECTED;
        case 1: return CONNECTED;
        case 2: return CAN_CONNECT;
        case 3: return CANNOT_CONNECT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ConnectionType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ConnectionType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ConnectionType>() {
            public ConnectionType findValueByNumber(int number) {
              return ConnectionType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.decentwallet.wallet.android.dht.proto.Message.getDescriptor().getEnumTypes().get(1);
    }

    private static final ConnectionType[] VALUES = values();

    public static ConnectionType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ConnectionType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:dht.pb.Message.ConnectionType)
  }

  public interface PeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dht.pb.Message.Peer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes id = 1;</code>
     * @return The id.
     */
    com.google.protobuf.ByteString getId();

    /**
     * <code>repeated bytes addrs = 2;</code>
     * @return A list containing the addrs.
     */
    java.util.List<com.google.protobuf.ByteString> getAddrsList();
    /**
     * <code>repeated bytes addrs = 2;</code>
     * @return The count of addrs.
     */
    int getAddrsCount();
    /**
     * <code>repeated bytes addrs = 2;</code>
     * @param index The index of the element to return.
     * @return The addrs at the given index.
     */
    com.google.protobuf.ByteString getAddrs(int index);

    /**
     * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
     * @return The enum numeric value on the wire for connection.
     */
    int getConnectionValue();
    /**
     * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
     * @return The connection.
     */
    org.decentwallet.wallet.android.dht.proto.Message.ConnectionType getConnection();
  }
  /**
   * Protobuf type {@code dht.pb.Message.Peer}
   */
  public static final class Peer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:dht.pb.Message.Peer)
      PeerOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Peer.newBuilder() to construct.
    private Peer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Peer() {
      id_ = com.google.protobuf.ByteString.EMPTY;
      addrs_ = emptyList(com.google.protobuf.ByteString.class);
      connection_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Peer();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_Peer_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_Peer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.decentwallet.wallet.android.dht.proto.Message.Peer.class, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    public static final int ADDRS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> addrs_ =
        emptyList(com.google.protobuf.ByteString.class);
    /**
     * <code>repeated bytes addrs = 2;</code>
     * @return A list containing the addrs.
     */
    @java.lang.Override
    public java.util.List<com.google.protobuf.ByteString>
        getAddrsList() {
      return addrs_;
    }
    /**
     * <code>repeated bytes addrs = 2;</code>
     * @return The count of addrs.
     */
    public int getAddrsCount() {
      return addrs_.size();
    }
    /**
     * <code>repeated bytes addrs = 2;</code>
     * @param index The index of the element to return.
     * @return The addrs at the given index.
     */
    public com.google.protobuf.ByteString getAddrs(int index) {
      return addrs_.get(index);
    }

    public static final int CONNECTION_FIELD_NUMBER = 3;
    private int connection_ = 0;
    /**
     * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
     * @return The enum numeric value on the wire for connection.
     */
    @java.lang.Override public int getConnectionValue() {
      return connection_;
    }
    /**
     * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
     * @return The connection.
     */
    @java.lang.Override public org.decentwallet.wallet.android.dht.proto.Message.ConnectionType getConnection() {
      org.decentwallet.wallet.android.dht.proto.Message.ConnectionType result = org.decentwallet.wallet.android.dht.proto.Message.ConnectionType.forNumber(connection_);
      return result == null ? org.decentwallet.wallet.android.dht.proto.Message.ConnectionType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!id_.isEmpty()) {
        output.writeBytes(1, id_);
      }
      for (int i = 0; i < addrs_.size(); i++) {
        output.writeBytes(2, addrs_.get(i));
      }
      if (connection_ != org.decentwallet.wallet.android.dht.proto.Message.ConnectionType.NOT_CONNECTED.getNumber()) {
        output.writeEnum(3, connection_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!id_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, id_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < addrs_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(addrs_.get(i));
        }
        size += dataSize;
        size += 1 * getAddrsList().size();
      }
      if (connection_ != org.decentwallet.wallet.android.dht.proto.Message.ConnectionType.NOT_CONNECTED.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, connection_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.decentwallet.wallet.android.dht.proto.Message.Peer)) {
        return super.equals(obj);
      }
      org.decentwallet.wallet.android.dht.proto.Message.Peer other = (org.decentwallet.wallet.android.dht.proto.Message.Peer) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getAddrsList()
          .equals(other.getAddrsList())) return false;
      if (connection_ != other.connection_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (getAddrsCount() > 0) {
        hash = (37 * hash) + ADDRS_FIELD_NUMBER;
        hash = (53 * hash) + getAddrsList().hashCode();
      }
      hash = (37 * hash) + CONNECTION_FIELD_NUMBER;
      hash = (53 * hash) + connection_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.decentwallet.wallet.android.dht.proto.Message.Peer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.decentwallet.wallet.android.dht.proto.Message.Peer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dht.pb.Message.Peer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dht.pb.Message.Peer)
        org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_Peer_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_Peer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.decentwallet.wallet.android.dht.proto.Message.Peer.class, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder.class);
      }

      // Construct using org.decentwallet.wallet.android.dht.proto.Message.Peer.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = com.google.protobuf.ByteString.EMPTY;
        addrs_ = emptyList(com.google.protobuf.ByteString.class);
        connection_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_Peer_descriptor;
      }

      @java.lang.Override
      public org.decentwallet.wallet.android.dht.proto.Message.Peer getDefaultInstanceForType() {
        return org.decentwallet.wallet.android.dht.proto.Message.Peer.getDefaultInstance();
      }

      @java.lang.Override
      public org.decentwallet.wallet.android.dht.proto.Message.Peer build() {
        org.decentwallet.wallet.android.dht.proto.Message.Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.decentwallet.wallet.android.dht.proto.Message.Peer buildPartial() {
        org.decentwallet.wallet.android.dht.proto.Message.Peer result = new org.decentwallet.wallet.android.dht.proto.Message.Peer(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.decentwallet.wallet.android.dht.proto.Message.Peer result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          addrs_.makeImmutable();
          result.addrs_ = addrs_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.connection_ = connection_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.decentwallet.wallet.android.dht.proto.Message.Peer) {
          return mergeFrom((org.decentwallet.wallet.android.dht.proto.Message.Peer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.decentwallet.wallet.android.dht.proto.Message.Peer other) {
        if (other == org.decentwallet.wallet.android.dht.proto.Message.Peer.getDefaultInstance()) return this;
        if (other.getId() != com.google.protobuf.ByteString.EMPTY) {
          setId(other.getId());
        }
        if (!other.addrs_.isEmpty()) {
          if (addrs_.isEmpty()) {
            addrs_ = other.addrs_;
            addrs_.makeImmutable();
            bitField0_ |= 0x00000002;
          } else {
            ensureAddrsIsMutable();
            addrs_.addAll(other.addrs_);
          }
          onChanged();
        }
        if (other.connection_ != 0) {
          setConnectionValue(other.getConnectionValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.ByteString v = input.readBytes();
                ensureAddrsIsMutable();
                addrs_.add(v);
                break;
              } // case 18
              case 24: {
                connection_ = input.readEnum();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>bytes id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> addrs_ = emptyList(com.google.protobuf.ByteString.class);
      private void ensureAddrsIsMutable() {
        if (!addrs_.isModifiable()) {
          addrs_ = makeMutableCopy(addrs_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated bytes addrs = 2;</code>
       * @return A list containing the addrs.
       */
      public java.util.List<com.google.protobuf.ByteString>
          getAddrsList() {
        addrs_.makeImmutable();
        return addrs_;
      }
      /**
       * <code>repeated bytes addrs = 2;</code>
       * @return The count of addrs.
       */
      public int getAddrsCount() {
        return addrs_.size();
      }
      /**
       * <code>repeated bytes addrs = 2;</code>
       * @param index The index of the element to return.
       * @return The addrs at the given index.
       */
      public com.google.protobuf.ByteString getAddrs(int index) {
        return addrs_.get(index);
      }
      /**
       * <code>repeated bytes addrs = 2;</code>
       * @param index The index to set the value at.
       * @param value The addrs to set.
       * @return This builder for chaining.
       */
      public Builder setAddrs(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAddrsIsMutable();
        addrs_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes addrs = 2;</code>
       * @param value The addrs to add.
       * @return This builder for chaining.
       */
      public Builder addAddrs(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ensureAddrsIsMutable();
        addrs_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes addrs = 2;</code>
       * @param values The addrs to add.
       * @return This builder for chaining.
       */
      public Builder addAllAddrs(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureAddrsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addrs_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes addrs = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddrs() {
        addrs_ = emptyList(com.google.protobuf.ByteString.class);
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      private int connection_ = 0;
      /**
       * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
       * @return The enum numeric value on the wire for connection.
       */
      @java.lang.Override public int getConnectionValue() {
        return connection_;
      }
      /**
       * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
       * @param value The enum numeric value on the wire for connection to set.
       * @return This builder for chaining.
       */
      public Builder setConnectionValue(int value) {
        connection_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
       * @return The connection.
       */
      @java.lang.Override
      public org.decentwallet.wallet.android.dht.proto.Message.ConnectionType getConnection() {
        org.decentwallet.wallet.android.dht.proto.Message.ConnectionType result = org.decentwallet.wallet.android.dht.proto.Message.ConnectionType.forNumber(connection_);
        return result == null ? org.decentwallet.wallet.android.dht.proto.Message.ConnectionType.UNRECOGNIZED : result;
      }
      /**
       * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
       * @param value The connection to set.
       * @return This builder for chaining.
       */
      public Builder setConnection(org.decentwallet.wallet.android.dht.proto.Message.ConnectionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        connection_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.dht.pb.Message.ConnectionType connection = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearConnection() {
        bitField0_ = (bitField0_ & ~0x00000004);
        connection_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:dht.pb.Message.Peer)
    }

    // @@protoc_insertion_point(class_scope:dht.pb.Message.Peer)
    private static final org.decentwallet.wallet.android.dht.proto.Message.Peer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.decentwallet.wallet.android.dht.proto.Message.Peer();
    }

    public static org.decentwallet.wallet.android.dht.proto.Message.Peer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Peer>
        PARSER = new com.google.protobuf.AbstractParser<Peer>() {
      @java.lang.Override
      public Peer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Peer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Peer> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.decentwallet.wallet.android.dht.proto.Message.Peer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 0;
  /**
   * <code>.dht.pb.Message.MessageType type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  @java.lang.Override public int getTypeValue() {
    return type_;
  }
  /**
   * <code>.dht.pb.Message.MessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public org.decentwallet.wallet.android.dht.proto.Message.MessageType getType() {
    org.decentwallet.wallet.android.dht.proto.Message.MessageType result = org.decentwallet.wallet.android.dht.proto.Message.MessageType.forNumber(type_);
    return result == null ? org.decentwallet.wallet.android.dht.proto.Message.MessageType.UNRECOGNIZED : result;
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>bytes key = 2;</code>
   * @return The key.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getKey() {
    return key_;
  }

  public static final int RECORD_FIELD_NUMBER = 3;
  private org.decentwallet.wallet.android.dht.proto.Record record_;
  /**
   * <code>.record.pb.Record record = 3;</code>
   * @return Whether the record field is set.
   */
  @java.lang.Override
  public boolean hasRecord() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.record.pb.Record record = 3;</code>
   * @return The record.
   */
  @java.lang.Override
  public org.decentwallet.wallet.android.dht.proto.Record getRecord() {
    return record_ == null ? org.decentwallet.wallet.android.dht.proto.Record.getDefaultInstance() : record_;
  }
  /**
   * <code>.record.pb.Record record = 3;</code>
   */
  @java.lang.Override
  public org.decentwallet.wallet.android.dht.proto.RecordOrBuilder getRecordOrBuilder() {
    return record_ == null ? org.decentwallet.wallet.android.dht.proto.Record.getDefaultInstance() : record_;
  }

  public static final int CLOSERPEERS_FIELD_NUMBER = 8;
  @SuppressWarnings("serial")
  private java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> closerPeers_;
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  @java.lang.Override
  public java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> getCloserPeersList() {
    return closerPeers_;
  }
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
      getCloserPeersOrBuilderList() {
    return closerPeers_;
  }
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  @java.lang.Override
  public int getCloserPeersCount() {
    return closerPeers_.size();
  }
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  @java.lang.Override
  public org.decentwallet.wallet.android.dht.proto.Message.Peer getCloserPeers(int index) {
    return closerPeers_.get(index);
  }
  /**
   * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
   */
  @java.lang.Override
  public org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder getCloserPeersOrBuilder(
      int index) {
    return closerPeers_.get(index);
  }

  public static final int PROVIDERPEERS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> providerPeers_;
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  @java.lang.Override
  public java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> getProviderPeersList() {
    return providerPeers_;
  }
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
      getProviderPeersOrBuilderList() {
    return providerPeers_;
  }
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  @java.lang.Override
  public int getProviderPeersCount() {
    return providerPeers_.size();
  }
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  @java.lang.Override
  public org.decentwallet.wallet.android.dht.proto.Message.Peer getProviderPeers(int index) {
    return providerPeers_.get(index);
  }
  /**
   * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
   */
  @java.lang.Override
  public org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder getProviderPeersOrBuilder(
      int index) {
    return providerPeers_.get(index);
  }

  public static final int CLUSTERLEVELRAW_FIELD_NUMBER = 10;
  private int clusterLevelRaw_ = 0;
  /**
   * <code>int32 clusterLevelRaw = 10;</code>
   * @return The clusterLevelRaw.
   */
  @java.lang.Override
  public int getClusterLevelRaw() {
    return clusterLevelRaw_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != org.decentwallet.wallet.android.dht.proto.Message.MessageType.PUT_VALUE.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (!key_.isEmpty()) {
      output.writeBytes(2, key_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getRecord());
    }
    for (int i = 0; i < closerPeers_.size(); i++) {
      output.writeMessage(8, closerPeers_.get(i));
    }
    for (int i = 0; i < providerPeers_.size(); i++) {
      output.writeMessage(9, providerPeers_.get(i));
    }
    if (clusterLevelRaw_ != 0) {
      output.writeInt32(10, clusterLevelRaw_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != org.decentwallet.wallet.android.dht.proto.Message.MessageType.PUT_VALUE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (!key_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, key_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getRecord());
    }
    for (int i = 0; i < closerPeers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, closerPeers_.get(i));
    }
    for (int i = 0; i < providerPeers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, providerPeers_.get(i));
    }
    if (clusterLevelRaw_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, clusterLevelRaw_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.decentwallet.wallet.android.dht.proto.Message)) {
      return super.equals(obj);
    }
    org.decentwallet.wallet.android.dht.proto.Message other = (org.decentwallet.wallet.android.dht.proto.Message) obj;

    if (type_ != other.type_) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (hasRecord() != other.hasRecord()) return false;
    if (hasRecord()) {
      if (!getRecord()
          .equals(other.getRecord())) return false;
    }
    if (!getCloserPeersList()
        .equals(other.getCloserPeersList())) return false;
    if (!getProviderPeersList()
        .equals(other.getProviderPeersList())) return false;
    if (getClusterLevelRaw()
        != other.getClusterLevelRaw()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (hasRecord()) {
      hash = (37 * hash) + RECORD_FIELD_NUMBER;
      hash = (53 * hash) + getRecord().hashCode();
    }
    if (getCloserPeersCount() > 0) {
      hash = (37 * hash) + CLOSERPEERS_FIELD_NUMBER;
      hash = (53 * hash) + getCloserPeersList().hashCode();
    }
    if (getProviderPeersCount() > 0) {
      hash = (37 * hash) + PROVIDERPEERS_FIELD_NUMBER;
      hash = (53 * hash) + getProviderPeersList().hashCode();
    }
    hash = (37 * hash) + CLUSTERLEVELRAW_FIELD_NUMBER;
    hash = (53 * hash) + getClusterLevelRaw();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.decentwallet.wallet.android.dht.proto.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.decentwallet.wallet.android.dht.proto.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.decentwallet.wallet.android.dht.proto.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.decentwallet.wallet.android.dht.proto.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Wire schema from libp2p/go-libp2p-kad-dht/pb/dht.proto.
   * </pre>
   *
   * Protobuf type {@code dht.pb.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:dht.pb.Message)
      org.decentwallet.wallet.android.dht.proto.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.decentwallet.wallet.android.dht.proto.Message.class, org.decentwallet.wallet.android.dht.proto.Message.Builder.class);
    }

    // Construct using org.decentwallet.wallet.android.dht.proto.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getRecordFieldBuilder();
        getCloserPeersFieldBuilder();
        getProviderPeersFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 0;
      key_ = com.google.protobuf.ByteString.EMPTY;
      record_ = null;
      if (recordBuilder_ != null) {
        recordBuilder_.dispose();
        recordBuilder_ = null;
      }
      if (closerPeersBuilder_ == null) {
        closerPeers_ = java.util.Collections.emptyList();
      } else {
        closerPeers_ = null;
        closerPeersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      if (providerPeersBuilder_ == null) {
        providerPeers_ = java.util.Collections.emptyList();
      } else {
        providerPeers_ = null;
        providerPeersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000010);
      clusterLevelRaw_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.decentwallet.wallet.android.dht.proto.DhtProtos.internal_static_dht_pb_Message_descriptor;
    }

    @java.lang.Override
    public org.decentwallet.wallet.android.dht.proto.Message getDefaultInstanceForType() {
      return org.decentwallet.wallet.android.dht.proto.Message.getDefaultInstance();
    }

    @java.lang.Override
    public org.decentwallet.wallet.android.dht.proto.Message build() {
      org.decentwallet.wallet.android.dht.proto.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.decentwallet.wallet.android.dht.proto.Message buildPartial() {
      org.decentwallet.wallet.android.dht.proto.Message result = new org.decentwallet.wallet.android.dht.proto.Message(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(org.decentwallet.wallet.android.dht.proto.Message result) {
      if (closerPeersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          closerPeers_ = java.util.Collections.unmodifiableList(closerPeers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.closerPeers_ = closerPeers_;
      } else {
        result.closerPeers_ = closerPeersBuilder_.build();
      }
      if (providerPeersBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0)) {
          providerPeers_ = java.util.Collections.unmodifiableList(providerPeers_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.providerPeers_ = providerPeers_;
      } else {
        result.providerPeers_ = providerPeersBuilder_.build();
      }
    }

    private void buildPartial0(org.decentwallet.wallet.android.dht.proto.Message result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.key_ = key_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.record_ = recordBuilder_ == null
            ? record_
            : recordBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.clusterLevelRaw_ = clusterLevelRaw_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.decentwallet.wallet.android.dht.proto.Message) {
        return mergeFrom((org.decentwallet.wallet.android.dht.proto.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.decentwallet.wallet.android.dht.proto.Message other) {
      if (other == org.decentwallet.wallet.android.dht.proto.Message.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.getKey() != com.google.protobuf.ByteString.EMPTY) {
        setKey(other.getKey());
      }
      if (other.hasRecord()) {
        mergeRecord(other.getRecord());
      }
      if (closerPeersBuilder_ == null) {
        if (!other.closerPeers_.isEmpty()) {
          if (closerPeers_.isEmpty()) {
            closerPeers_ = other.closerPeers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCloserPeersIsMutable();
            closerPeers_.addAll(other.closerPeers_);
          }
          onChanged();
        }
      } else {
        if (!other.closerPeers_.isEmpty()) {
          if (closerPeersBuilder_.isEmpty()) {
            closerPeersBuilder_.dispose();
            closerPeersBuilder_ = null;
            closerPeers_ = other.closerPeers_;
            bitField0_ = (bitField0_ & ~0x00000008);
            closerPeersBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCloserPeersFieldBuilder() : null;
          } else {
            closerPeersBuilder_.addAllMessages(other.closerPeers_);
          }
        }
      }
      if (providerPeersBuilder_ == null) {
        if (!other.providerPeers_.isEmpty()) {
          if (providerPeers_.isEmpty()) {
            providerPeers_ = other.providerPeers_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureProviderPeersIsMutable();
            providerPeers_.addAll(other.providerPeers_);
          }
          onChanged();
        }
      } else {
        if (!other.providerPeers_.isEmpty()) {
          if (providerPeersBuilder_.isEmpty()) {
            providerPeersBuilder_.dispose();
            providerPeersBuilder_ = null;
            providerPeers_ = other.providerPeers_;
            bitField0_ = (bitField0_ & ~0x00000010);
            providerPeersBuilder_ =
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getProviderPeersFieldBuilder() : null;
          } else {
            providerPeersBuilder_.addAllMessages(other.providerPeers_);
          }
        }
      }
      if (other.getClusterLevelRaw() != 0) {
        setClusterLevelRaw(other.getClusterLevelRaw());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              type_ = input.readEnum();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              key_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getRecordFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 66: {
              org.decentwallet.wallet.android.dht.proto.Message.Peer m =
                  input.readMessage(
                      org.decentwallet.wallet.android.dht.proto.Message.Peer.parser(),
                      extensionRegistry);
              if (closerPeersBuilder_ == null) {
                ensureCloserPeersIsMutable();
                closerPeers_.add(m);
              } else {
                closerPeersBuilder_.addMessage(m);
              }
              break;
            } // case 66
            case 74: {
              org.decentwallet.wallet.android.dht.proto.Message.Peer m =
                  input.readMessage(
                      org.decentwallet.wallet.android.dht.proto.Message.Peer.parser(),
                      extensionRegistry);
              if (providerPeersBuilder_ == null) {
                ensureProviderPeersIsMutable();
                providerPeers_.add(m);
              } else {
                providerPeersBuilder_.addMessage(m);
              }
              break;
            } // case 74
            case 80: {
              clusterLevelRaw_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 0;
    /**
     * <code>.dht.pb.Message.MessageType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.dht.pb.Message.MessageType type = 1;</code>
     * @param value The enum numeric value on the wire for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.dht.pb.Message.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public org.decentwallet.wallet.android.dht.proto.Message.MessageType getType() {
      org.decentwallet.wallet.android.dht.proto.Message.MessageType result = org.decentwallet.wallet.android.dht.proto.Message.MessageType.forNumber(type_);
      return result == null ? org.decentwallet.wallet.android.dht.proto.Message.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.dht.pb.Message.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(org.decentwallet.wallet.android.dht.proto.Message.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.dht.pb.Message.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString key_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes key = 2;</code>
     * @return The key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getKey() {
      return key_;
    }
    /**
     * <code>bytes key = 2;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      key_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bytes key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      bitField0_ = (bitField0_ & ~0x00000002);
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }

    private org.decentwallet.wallet.android.dht.proto.Record record_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.decentwallet.wallet.android.dht.proto.Record, org.decentwallet.wallet.android.dht.proto.Record.Builder, org.decentwallet.wallet.android.dht.proto.RecordOrBuilder> recordBuilder_;
    /**
     * <code>.record.pb.Record record = 3;</code>
     * @return Whether the record field is set.
     */
    public boolean hasRecord() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     * @return The record.
     */
    public org.decentwallet.wallet.android.dht.proto.Record getRecord() {
      if (recordBuilder_ == null) {
        return record_ == null ? org.decentwallet.wallet.android.dht.proto.Record.getDefaultInstance() : record_;
      } else {
        return recordBuilder_.getMessage();
      }
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     */
    public Builder setRecord(org.decentwallet.wallet.android.dht.proto.Record value) {
      if (recordBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        record_ = value;
      } else {
        recordBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     */
    public Builder setRecord(
        org.decentwallet.wallet.android.dht.proto.Record.Builder builderForValue) {
      if (recordBuilder_ == null) {
        record_ = builderForValue.build();
      } else {
        recordBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     */
    public Builder mergeRecord(org.decentwallet.wallet.android.dht.proto.Record value) {
      if (recordBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          record_ != null &&
          record_ != org.decentwallet.wallet.android.dht.proto.Record.getDefaultInstance()) {
          getRecordBuilder().mergeFrom(value);
        } else {
          record_ = value;
        }
      } else {
        recordBuilder_.mergeFrom(value);
      }
      if (record_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     */
    public Builder clearRecord() {
      bitField0_ = (bitField0_ & ~0x00000004);
      record_ = null;
      if (recordBuilder_ != null) {
        recordBuilder_.dispose();
        recordBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Record.Builder getRecordBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getRecordFieldBuilder().getBuilder();
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.RecordOrBuilder getRecordOrBuilder() {
      if (recordBuilder_ != null) {
        return recordBuilder_.getMessageOrBuilder();
      } else {
        return record_ == null ?
            org.decentwallet.wallet.android.dht.proto.Record.getDefaultInstance() : record_;
      }
    }
    /**
     * <code>.record.pb.Record record = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.decentwallet.wallet.android.dht.proto.Record, org.decentwallet.wallet.android.dht.proto.Record.Builder, org.decentwallet.wallet.android.dht.proto.RecordOrBuilder>
        getRecordFieldBuilder() {
      if (recordBuilder_ == null) {
        recordBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.decentwallet.wallet.android.dht.proto.Record, org.decentwallet.wallet.android.dht.proto.Record.Builder, org.decentwallet.wallet.android.dht.proto.RecordOrBuilder>(
                getRecord(),
                getParentForChildren(),
                isClean());
        record_ = null;
      }
      return recordBuilder_;
    }

    private java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> closerPeers_ =
      java.util.Collections.emptyList();
    private void ensureCloserPeersIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        closerPeers_ = new java.util.ArrayList<org.decentwallet.wallet.android.dht.proto.Message.Peer>(closerPeers_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.decentwallet.wallet.android.dht.proto.Message.Peer, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder, org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder> closerPeersBuilder_;

    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> getCloserPeersList() {
      if (closerPeersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(closerPeers_);
      } else {
        return closerPeersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public int getCloserPeersCount() {
      if (closerPeersBuilder_ == null) {
        return closerPeers_.size();
      } else {
        return closerPeersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer getCloserPeers(int index) {
      if (closerPeersBuilder_ == null) {
        return closerPeers_.get(index);
      } else {
        return closerPeersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder setCloserPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer value) {
      if (closerPeersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCloserPeersIsMutable();
        closerPeers_.set(index, value);
        onChanged();
      } else {
        closerPeersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder setCloserPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder builderForValue) {
      if (closerPeersBuilder_ == null) {
        ensureCloserPeersIsMutable();
        closerPeers_.set(index, builderForValue.build());
        onChanged();
      } else {
        closerPeersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder addCloserPeers(org.decentwallet.wallet.android.dht.proto.Message.Peer value) {
      if (closerPeersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCloserPeersIsMutable();
        closerPeers_.add(value);
        onChanged();
      } else {
        closerPeersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder addCloserPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer value) {
      if (closerPeersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCloserPeersIsMutable();
        closerPeers_.add(index, value);
        onChanged();
      } else {
        closerPeersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder addCloserPeers(
        org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder builderForValue) {
      if (closerPeersBuilder_ == null) {
        ensureCloserPeersIsMutable();
        closerPeers_.add(builderForValue.build());
        onChanged();
      } else {
        closerPeersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder addCloserPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder builderForValue) {
      if (closerPeersBuilder_ == null) {
        ensureCloserPeersIsMutable();
        closerPeers_.add(index, builderForValue.build());
        onChanged();
      } else {
        closerPeersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder addAllCloserPeers(
        java.lang.Iterable<? extends org.decentwallet.wallet.android.dht.proto.Message.Peer> values) {
      if (closerPeersBuilder_ == null) {
        ensureCloserPeersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, closerPeers_);
        onChanged();
      } else {
        closerPeersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder clearCloserPeers() {
      if (closerPeersBuilder_ == null) {
        closerPeers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        closerPeersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public Builder removeCloserPeers(int index) {
      if (closerPeersBuilder_ == null) {
        ensureCloserPeersIsMutable();
        closerPeers_.remove(index);
        onChanged();
      } else {
        closerPeersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder getCloserPeersBuilder(
        int index) {
      return getCloserPeersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder getCloserPeersOrBuilder(
        int index) {
      if (closerPeersBuilder_ == null) {
        return closerPeers_.get(index);  } else {
        return closerPeersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public java.util.List<? extends org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
         getCloserPeersOrBuilderList() {
      if (closerPeersBuilder_ != null) {
        return closerPeersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(closerPeers_);
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder addCloserPeersBuilder() {
      return getCloserPeersFieldBuilder().addBuilder(
          org.decentwallet.wallet.android.dht.proto.Message.Peer.getDefaultInstance());
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder addCloserPeersBuilder(
        int index) {
      return getCloserPeersFieldBuilder().addBuilder(
          index, org.decentwallet.wallet.android.dht.proto.Message.Peer.getDefaultInstance());
    }
    /**
     * <code>repeated .dht.pb.Message.Peer closerPeers = 8;</code>
     */
    public java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder>
         getCloserPeersBuilderList() {
      return getCloserPeersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.decentwallet.wallet.android.dht.proto.Message.Peer, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder, org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
        getCloserPeersFieldBuilder() {
      if (closerPeersBuilder_ == null) {
        closerPeersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.decentwallet.wallet.android.dht.proto.Message.Peer, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder, org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>(
                closerPeers_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        closerPeers_ = null;
      }
      return closerPeersBuilder_;
    }

    private java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> providerPeers_ =
      java.util.Collections.emptyList();
    private void ensureProviderPeersIsMutable() {
      if (!((bitField0_ & 0x00000010) != 0)) {
        providerPeers_ = new java.util.ArrayList<org.decentwallet.wallet.android.dht.proto.Message.Peer>(providerPeers_);
        bitField0_ |= 0x00000010;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.decentwallet.wallet.android.dht.proto.Message.Peer, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder, org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder> providerPeersBuilder_;

    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer> getProviderPeersList() {
      if (providerPeersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(providerPeers_);
      } else {
        return providerPeersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public int getProviderPeersCount() {
      if (providerPeersBuilder_ == null) {
        return providerPeers_.size();
      } else {
        return providerPeersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer getProviderPeers(int index) {
      if (providerPeersBuilder_ == null) {
        return providerPeers_.get(index);
      } else {
        return providerPeersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder setProviderPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer value) {
      if (providerPeersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProviderPeersIsMutable();
        providerPeers_.set(index, value);
        onChanged();
      } else {
        providerPeersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder setProviderPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder builderForValue) {
      if (providerPeersBuilder_ == null) {
        ensureProviderPeersIsMutable();
        providerPeers_.set(index, builderForValue.build());
        onChanged();
      } else {
        providerPeersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder addProviderPeers(org.decentwallet.wallet.android.dht.proto.Message.Peer value) {
      if (providerPeersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProviderPeersIsMutable();
        providerPeers_.add(value);
        onChanged();
      } else {
        providerPeersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder addProviderPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer value) {
      if (providerPeersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureProviderPeersIsMutable();
        providerPeers_.add(index, value);
        onChanged();
      } else {
        providerPeersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder addProviderPeers(
        org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder builderForValue) {
      if (providerPeersBuilder_ == null) {
        ensureProviderPeersIsMutable();
        providerPeers_.add(builderForValue.build());
        onChanged();
      } else {
        providerPeersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder addProviderPeers(
        int index, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder builderForValue) {
      if (providerPeersBuilder_ == null) {
        ensureProviderPeersIsMutable();
        providerPeers_.add(index, builderForValue.build());
        onChanged();
      } else {
        providerPeersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder addAllProviderPeers(
        java.lang.Iterable<? extends org.decentwallet.wallet.android.dht.proto.Message.Peer> values) {
      if (providerPeersBuilder_ == null) {
        ensureProviderPeersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, providerPeers_);
        onChanged();
      } else {
        providerPeersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder clearProviderPeers() {
      if (providerPeersBuilder_ == null) {
        providerPeers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
      } else {
        providerPeersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public Builder removeProviderPeers(int index) {
      if (providerPeersBuilder_ == null) {
        ensureProviderPeersIsMutable();
        providerPeers_.remove(index);
        onChanged();
      } else {
        providerPeersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder getProviderPeersBuilder(
        int index) {
      return getProviderPeersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder getProviderPeersOrBuilder(
        int index) {
      if (providerPeersBuilder_ == null) {
        return providerPeers_.get(index);  } else {
        return providerPeersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public java.util.List<? extends org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
         getProviderPeersOrBuilderList() {
      if (providerPeersBuilder_ != null) {
        return providerPeersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(providerPeers_);
      }
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder addProviderPeersBuilder() {
      return getProviderPeersFieldBuilder().addBuilder(
          org.decentwallet.wallet.android.dht.proto.Message.Peer.getDefaultInstance());
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder addProviderPeersBuilder(
        int index) {
      return getProviderPeersFieldBuilder().addBuilder(
          index, org.decentwallet.wallet.android.dht.proto.Message.Peer.getDefaultInstance());
    }
    /**
     * <code>repeated .dht.pb.Message.Peer providerPeers = 9;</code>
     */
    public java.util.List<org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder>
         getProviderPeersBuilderList() {
      return getProviderPeersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        org.decentwallet.wallet.android.dht.proto.Message.Peer, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder, org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>
        getProviderPeersFieldBuilder() {
      if (providerPeersBuilder_ == null) {
        providerPeersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            org.decentwallet.wallet.android.dht.proto.Message.Peer, org.decentwallet.wallet.android.dht.proto.Message.Peer.Builder, org.decentwallet.wallet.android.dht.proto.Message.PeerOrBuilder>(
                providerPeers_,
                ((bitField0_ & 0x00000010) != 0),
                getParentForChildren(),
                isClean());
        providerPeers_ = null;
      }
      return providerPeersBuilder_;
    }

    private int clusterLevelRaw_ ;
    /**
     * <code>int32 clusterLevelRaw = 10;</code>
     * @return The clusterLevelRaw.
     */
    @java.lang.Override
    public int getClusterLevelRaw() {
      return clusterLevelRaw_;
    }
    /**
     * <code>int32 clusterLevelRaw = 10;</code>
     * @param value The clusterLevelRaw to set.
     * @return This builder for chaining.
     */
    public Builder setClusterLevelRaw(int value) {

      clusterLevelRaw_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 clusterLevelRaw = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearClusterLevelRaw() {
      bitField0_ = (bitField0_ & ~0x00000020);
      clusterLevelRaw_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:dht.pb.Message)
  }

  // @@protoc_insertion_point(class_scope:dht.pb.Message)
  private static final org.decentwallet.wallet.android.dht.proto.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.decentwallet.wallet.android.dht.proto.Message();
  }

  public static org.decentwallet.wallet.android.dht.proto.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.decentwallet.wallet.android.dht.proto.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}
