// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

// Protobuf Java Version: 3.25.5
package org.decentwallet.wallet.android.dht.proto;

public final class RecordProtos {
  private RecordProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_record_pb_Record_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_record_pb_Record_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014record.proto\022\trecord.pb\":\n\006Record\022\013\n\003k" +
      "ey\030\001 \001(\014\022\r\n\005value\030\002 \001(\014\022\024\n\014timeReceived\030" +
      "\005 \001(\tB;\n)org.decentwallet.wallet.android" +
      ".dht.protoB\014RecordProtosP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_record_pb_Record_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_record_pb_Record_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_record_pb_Record_descriptor,
        new java.lang.String[] { "Key", "Value", "TimeReceived", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
