// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: record.proto

// Protobuf Java Version: 3.25.5
package org.decentwallet.wallet.android.dht.proto;

public interface RecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:record.pb.Record)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes key = 1;</code>
   * @return The key.
   */
  com.google.protobuf.ByteString getKey();

  /**
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();

  /**
   * <code>string timeReceived = 5;</code>
   * @return The timeReceived.
   */
  java.lang.String getTimeReceived();
  /**
   * <code>string timeReceived = 5;</code>
   * @return The bytes for timeReceived.
   */
  com.google.protobuf.ByteString
      getTimeReceivedBytes();
}
