"""Secret-preserving wallet primitives."""

from .container import (
    CURRENT_FORMAT_VERSION,
    Wallet,
    WalletError,
    WalletLockedError,
    PasswordPolicyError,
    UnlockFailed,
    InvalidContainer,
    UnsupportedFormat,
    StorageFailure,
)
from .signer import (
    InvalidSigningInput,
    KeyGenerationError,
    SignerCapability,
    SignerError,
    SignerUnavailable,
)
from .identity import (
    ConsentDecision,
    ConsentTranscript,
    DispatchUnknown,
    ExpiredPublication,
    IdentityAdapterError,
    IdentityState,
    IdentityTransport,
    InMemoryReplayNonceStore,
    InvalidIdentityRequest,
    ReplayNonceStore,
    InvalidIdentityState,
    PublishStatus,
    RegistryAdapter,
    StalePublication,
    SubmissionResult,
    TransportFailure,
    build_identity_update,
)

__all__ = [
    "CURRENT_FORMAT_VERSION",
    "Wallet",
    "WalletError",
    "WalletLockedError",
    "PasswordPolicyError",
    "UnlockFailed",
    "InvalidContainer",
    "UnsupportedFormat",
    "StorageFailure",
    "InvalidSigningInput",
    "KeyGenerationError",
    "SignerCapability",
    "SignerError",
    "SignerUnavailable",
    "ConsentDecision",
    "ConsentTranscript",
    "DispatchUnknown",
    "ExpiredPublication",
    "IdentityAdapterError",
    "IdentityState",
    "IdentityTransport",
    "InMemoryReplayNonceStore",
    "InvalidIdentityRequest",
    "ReplayNonceStore",
    "InvalidIdentityState",
    "PublishStatus",
    "RegistryAdapter",
    "StalePublication",
    "SubmissionResult",
    "TransportFailure",
    "build_identity_update",
]
