Pkg.Desc=System Image Page Size 16k x86_64 with Google Play.
Pkg.Revision=5
Pkg.Dependencies=emulator#36.5.11
AndroidVersion.ApiLevel=37.2
AndroidVersion.ExtensionLevel=24
AndroidVersion.IsBaseSdk=true
SystemImage.Abi=x86_64
SystemImage.TagId=google_apis_playstore,page_size_16kb
SystemImage.TagDisplay=Google APIs PlayStore,Page Size 16KB
SystemImage.GpuSupport=true
Addon.VendorId=google
Addon.VendorDisplay=Google Inc.
AndroidVersion.PreviewSdkInt=0
AndroidVersion.BetaVersion=
